In [75]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [76]:
df=pd.read_csv(r"C:\Users\burha\OneDrive\practice_datasets\jobanalyserproject\naukri_com-job_sample.csv")

In [77]:
df.head()

,company,education,experience,industry,jobdescription,jobid,joblocation_address,jobtitle,numberofpositions,payrate,postdate,site_name,skills,uniq_id
0,MM Media Pvt Ltd,UG: B.Tech/B.E. - Any Specialization PG:Any Po...,0 - 1 yrs,Media / Entertainment / Internet,Job Description Send me Jobs like this Quali...,210516002263,Chennai,Walkin Data Entry Operator (night Shift),NaN,"1,50,000 - 2,25,000 P.A",2016-05-21 19:30:00 +0000,NaN,ITES,43b19632647068535437c774b6ca6cf8
1,find live infotech,UG: B.Tech/B.E. - Any Specialization PG:MBA/PG...,0 - 0 yrs,Advertising / PR / MR / Event Management,Job Description Send me Jobs like this Quali...,210516002391,Chennai,Work Based Onhome Based Part Time.,60.0,"1,50,000 - 2,50,000 P.A. 20000",2016-05-21 19:30:00 +0000,NaN,Marketing,d4c72325e57f89f364812b5ed5a795f0
2,Softtech Career Infosystem Pvt. Ltd,UG: Any Graduate - Any Specialization PG:Any P...,4 - 8 yrs,IT-Software / Software Services,Job Description Send me Jobs like this - as ...,101016900534,Bengaluru,Pl/sql Developer - SQL,NaN,Not Disclosed by Recruiter,2016-10-13 16:20:55 +0000,NaN,IT Software - Application Programming,c47df6f4cfdf5b46f1fd713ba61b9eba
3,Onboard HRServices LLP,UG: Any Graduate - Any Specialization PG:CA Do...,11 - 15 yrs,Banking / Financial Services / Broking,Job Description Send me Jobs like this - Inv...,81016900536,"Mumbai, Bengaluru, Kolkata, Chennai, Coimbator...",Manager/ad/partner - Indirect Tax - CA,NaN,Not Disclosed by Recruiter,2016-10-13 16:20:55 +0000,NaN,Accounts,115d28f140f694dd1cc61c53d03c66ae
4,Spire Technologies and Solutions Pvt. Ltd.,UG: B.Tech/B.E. - Any Specialization PG:Any Po...,6 - 8 yrs,IT-Software / Software Services,Job Description Send me Jobs like this Pleas...,120916002122,Bengaluru,JAVA Technical Lead (6-8 yrs) -,4.0,Not Disclosed by Recruiter,2016-10-13 16:20:55 +0000,NaN,IT Software - Application Programming,a12553fc03bc7bcced8b1bb8963f97b4

In [78]:
df.shape

(22000, 14)

In [79]:
df.isnull().sum()

company                    4
education               1996
experience                 4
industry                   5
jobdescription             4
jobid                      0
joblocation_address      501
jobtitle                   0
numberofpositions      17536
payrate                   97
postdate                  23
site_name              18013
skills                   528
uniq_id                    0
dtype: int64

In [80]:
df.drop(columns=['numberofpositions' , 'site_name','education','jobid','postdate','uniq_id'], inplace=True, axis=1)

In [81]:
df.dropna(subset=['company','jobdescription','experience','skills', 'payrate'],inplace=True)

In [82]:
df[df.duplicated()]

,company,experience,industry,jobdescription,joblocation_address,jobtitle,payrate,skills
766,STARPOWERZ Human Resources Private Limited,0 - 2 yrs,Insurance,Job Description Send me Jobs like this Greet...,"Hyderabad, Mumbai, Bengaluru","Wealth Planning Officer (wpo) - Hyderabad, Ban...","1,50,000 - 2,25,000 P.A",Sales
867,TRUGlobal Software India Pvt Ltd,4 - 8 yrs,IT-Software / Software Services,Job Description Send me Jobs like this 1. 4+...,Bengaluru,Microsoft Dynamics AX Technical Consultant,"5,00,000 - 12,00,000 P.A",IT Software - Application Programming
3502,Innova Solutions Private Limited,2 - 7 yrs,IT-Software / Software Services,Job Description Send me Jobs like this Exp: ...,Hyderabad / Secunderabad,Urgent Opening for L2 Network Engineer || Hyde...,Best in Industry,IT Software - Application Programming
4463,Talent Excellence Management Consultant hiring...,10 - 15 yrs,Automobile / Auto Anciliary / Auto Components,Job Description Send me Jobs like this CHECK...,Chennai,Assistant Manager - Production - ppc - auto mn...,"3,50,000 - 4,25,000 P.A",Production
6771,Diksha Technologies,8 - 13 yrs,IT-Software / Software Services,Job Description Send me Jobs like this Stron...,"Bengaluru/Bangalore , Gurgaon",Intec Interconnect /IOA v7 Experts,Not Disclosed by Recruiter,IT Software - Application Programming
...,...,...,...,...,...,...,...,...
21224,EDIFICE TECH SOLUTIONS,4 - 8 yrs,IT-Software / Software Services,Job Description Send me Jobs like this Urgen...,Hyderabad,Hiring for Matlab Engineer,Not Disclosed by Recruiter,IT Software - Application Programming
21461,Future Point technologies hiring for Nipun Net...,0 - 2 yrs,IT-Software / Software Services,Job Description Send me Jobs like this Perfo...,"Hyderabad, Visakhapatnam, Vijayawada",Diploma with GPS Experience,"1,25,000 - 3,75,000 P.A",Production
21476,Anantha Cyber Tech Pvt Ltd,4 - 6 yrs,IT-Software / Software Services,Job Description Send me Jobs like this Hi Al...,Hyderabad,Hiring for Application Packaging Consultant at...,Not Disclosed by Recruiter,IT Software - Application Programming
21546,K SQUARE INDIA TECHNOLOGIES PVT LTD,5 - 9 yrs,IT-Software / Software Services,Job Description Send me Jobs like this We re...,"Mumbai, Bengaluru, Hyderabad",Need SAP FICO / MM / SD with CIN,Not Disclosed by Recruiter,IT Software - Application Programming
21589,Cucumber Consultants,5 - 8 yrs,Retail / Wholesale,Job Description Send me Jobs like this Candi...,Hyderabad,Operations Manager-hyderabad,"4,00,000 - 6,00,000 P.A",ITES

In [83]:
df.drop_duplicates(inplace=True)

In [84]:
df.isnull().sum()

company                  0
experience               0
industry                 0
jobdescription           0
joblocation_address    493
jobtitle                 0
payrate                  0
skills                   0
dtype: int64

In [85]:
df.shape

(21317, 8)

In [86]:
df['joblocation_address']=df['joblocation_address'].fillna('Remote')

In [87]:
df.head()

,company,experience,industry,jobdescription,joblocation_address,jobtitle,payrate,skills
0,MM Media Pvt Ltd,0 - 1 yrs,Media / Entertainment / Internet,Job Description Send me Jobs like this Quali...,Chennai,Walkin Data Entry Operator (night Shift),"1,50,000 - 2,25,000 P.A",ITES
1,find live infotech,0 - 0 yrs,Advertising / PR / MR / Event Management,Job Description Send me Jobs like this Quali...,Chennai,Work Based Onhome Based Part Time.,"1,50,000 - 2,50,000 P.A. 20000",Marketing
2,Softtech Career Infosystem Pvt. Ltd,4 - 8 yrs,IT-Software / Software Services,Job Description Send me Jobs like this - as ...,Bengaluru,Pl/sql Developer - SQL,Not Disclosed by Recruiter,IT Software - Application Programming
3,Onboard HRServices LLP,11 - 15 yrs,Banking / Financial Services / Broking,Job Description Send me Jobs like this - Inv...,"Mumbai, Bengaluru, Kolkata, Chennai, Coimbator...",Manager/ad/partner - Indirect Tax - CA,Not Disclosed by Recruiter,Accounts
4,Spire Technologies and Solutions Pvt. Ltd.,6 - 8 yrs,IT-Software / Software Services,Job Description Send me Jobs like this Pleas...,Bengaluru,JAVA Technical Lead (6-8 yrs) -,Not Disclosed by Recruiter,IT Software - Application Programming

In [88]:
df['payrate'].nunique()

1795

In [89]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 21317 entries, 0 to 21999
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   company              21317 non-null  object
 1   experience           21317 non-null  object
 2   industry             21317 non-null  object
 3   jobdescription       21317 non-null  object
 4   joblocation_address  21317 non-null  object
 5   jobtitle             21317 non-null  object
 6   payrate              21317 non-null  object
 7   skills               21317 non-null  object
dtypes: object(8)
memory usage: 1.5+ MB

In [90]:
df['Min_Exp_years']=df['experience'].str.split('-').str[0]
df['Max_Exp_years'] = df['experience'].str.replace('yrs','').str.split('-').str[1].str.strip()

In [91]:
df

,company,experience,industry,jobdescription,joblocation_address,jobtitle,payrate,skills,Min_Exp_years,Max_Exp_years
0,MM Media Pvt Ltd,0 - 1 yrs,Media / Entertainment / Internet,Job Description Send me Jobs like this Quali...,Chennai,Walkin Data Entry Operator (night Shift),"1,50,000 - 2,25,000 P.A",ITES,0,1
1,find live infotech,0 - 0 yrs,Advertising / PR / MR / Event Management,Job Description Send me Jobs like this Quali...,Chennai,Work Based Onhome Based Part Time.,"1,50,000 - 2,50,000 P.A. 20000",Marketing,0,0
2,Softtech Career Infosystem Pvt. Ltd,4 - 8 yrs,IT-Software / Software Services,Job Description Send me Jobs like this - as ...,Bengaluru,Pl/sql Developer - SQL,Not Disclosed by Recruiter,IT Software - Application Programming,4,8
3,Onboard HRServices LLP,11 - 15 yrs,Banking / Financial Services / Broking,Job Description Send me Jobs like this - Inv...,"Mumbai, Bengaluru, Kolkata, Chennai, Coimbator...",Manager/ad/partner - Indirect Tax - CA,Not Disclosed by Recruiter,Accounts,11,15
4,Spire Technologies and Solutions Pvt. Ltd.,6 - 8 yrs,IT-Software / Software Services,Job Description Send me Jobs like this Pleas...,Bengaluru,JAVA Technical Lead (6-8 yrs) -,Not Disclosed by Recruiter,IT Software - Application Programming,6,8
...,...,...,...,...,...,...,...,...,...,...
21995,Morgan Stanley Advantage Services Pvt. Ltd.,9 - 13 yrs,Banking / Financial Services / Broking,Job Description Send me Jobs like this Greet...,Bengaluru,Quality Assurance - VP with Morgan Stanley Ban...,Not Disclosed by Recruiter,IT Software - QA & Testing,9,13
21996,Careernet Technologies Pvt Ltd hiring for Client,3 - 5 yrs,IT-Software / Software Services,Job Description Send me Jobs like this Looki...,"Bengaluru, Gurgaon",Java Backend Developers for a Product Company,"8,50,000 - 14,00,000 P.A",IT Software - Application Programming,3,5
21997,Musk - Startup,2 - 4 yrs,Internet / Ecommerce,Job Description Send me Jobs like this Work ...,Bengaluru,Full Stack Development Engineer,Not Disclosed by Recruiter,IT Software - Application Programming,2,4
21998,Confidential,7 - 12 yrs,IT-Software / Software Services,Job Description Send me Jobs like this We ar...,"Delhi NCR, Bengaluru",Sr UI Developer/ Technical Lead - Html/ CSS/ J...,Not Disclosed by Recruiter,IT Software - Application Programming,7,12
21999,Cambio Consulting India Pvt Ltd,5 - 10 yrs,IT-Software / Software Services,Job Description Send me Jobs like this Job d...,Bengaluru,RF Firmware Engineers,"12,00,000 - 22,00,000 P.A",IT Software - System Programming,5,10

In [92]:
df['Max_Exp_years'].isna().sum()

15

In [93]:
df[df['experience'].str.contains('Not Mentioned')]

,company,experience,industry,jobdescription,joblocation_address,jobtitle,payrate,skills,Min_Exp_years,Max_Exp_years
1138,International Centre for Theoretical Sciences,Not Mentioned,Education / Teaching / Training,Job Description Send me Jobs like this Eligi...,Bengaluru,Postdoctoral Fellowship in Physics & Mathematics,"Salary structure is: 32,000 INR (for thesis su...",Medical,Not Mentioned,NaN
7806,Rajiv Gandhi Super Speciality Hospital,Not Mentioned,Medical / Healthcare / Hospitals,Job Description Send me Jobs like this No. o...,Delhi,Senior Resident - (Cardiac Surgery),Monthly Salary: Pay Scale of Rs.15600- 39100/-...,Medical,Not Mentioned,NaN
7873,University of Delhi,Not Mentioned,Education / Teaching / Training,Job Description Send me Jobs like this Advt....,Delhi,Tech. Assistant (Contractual),"Pay Scale : Rs. 15,800/- per month",Engineering Design,Not Mentioned,NaN
8774,Information Technology Research Academy (ITRA),Not Mentioned,Education / Teaching / Training,Job Description Send me Jobs like this Advt....,Delhi,Senior Scientific Officer,"Salary :Consolidated Rs. 55,000/- per month",IT Software - Application Programming,Not Mentioned,NaN
8904,Information Technology Research Academy (ITRA),Not Mentioned,Education / Teaching / Training,Job Description Send me Jobs like this Advt....,Delhi,Network Administrators,"Salary :Consolidated Rs. 46,000/- per month",IT Software - Network Administration,Not Mentioned,NaN
9795,Electronics and Radar Development Establishment,Not Mentioned,Government / Defence,Job Description Send me Jobs like this Adver...,Bengaluru/Bangalore,JRF - Mechanical,"Monthly Stipend: RS. 25,000/-",Engineering Design,Not Mentioned,NaN
9903,Electronics and Radar Development Establishment,Not Mentioned,Government / Defence,Job Description Send me Jobs like this Adver...,Bengaluru/Bangalore,JRF - Electronics,"Monthly Stipend: RS. 25,000/-",Engineering Design,Not Mentioned,NaN
10474,"Indian Institute Of Science, Bangalore",Not Mentioned,Education / Teaching / Training,Job Description Send me Jobs like this No. o...,Bengaluru/Bangalore,Instructor,"Salary: RS.(52,000-5,000 - 77,000)",Teaching,Not Mentioned,NaN
10594,Electronics and Radar Development Establishment,Not Mentioned,Government / Defence,Job Description Send me Jobs like this Adver...,Bengaluru/Bangalore,JRF - Electrical,"Monthly Stipend: RS. 25,000/-",Engineering Design,Not Mentioned,NaN
10859,Bangalore Metro Rail Corporation Limited,Not Mentioned,Courier / Transportation / Freight / Warehousing,Job Description Send me Jobs like this No of...,Bengaluru/Bangalore,Assistant Engineer,Pay : CDA Pay Scale : 9300 - 34800 + GP 4800 G...,Site Engineering,Not Mentioned,NaN
21295,NMDC Limited,Not Mentioned,Iron and Steel,Job Description Send me Jobs like this Emplo...,Hyderabad,Asst. General Manager (Safety) (E5),Scale of Pay (Rs.) 43200-3%-66000/-,Production,Not Mentioned,NaN
21315,Directorate of Poultry Research,Not Mentioned,Government / Defence,Job Description Send me Jobs like this Vacan...,Hyderabad,Lower Divisional Clerk,Pay Band + Grade Pay Rs. 5200-20200+Rs.1900/-,Executive Assistant,Not Mentioned,NaN
21397,NMDC Limited,Not Mentioned,Iron and Steel,Job Description Send me Jobs like this Emplo...,Hyderabad,Asst. Manager (Safety) (E1),Scale of Pay (Rs.) 20600-3%-46500/-,Production,Not Mentioned,NaN
21430,NMDC Limited,Not Mentioned,Iron and Steel,Job Description Send me Jobs like this Emplo...,Hyderabad,Sr. Manager (Safety) (E4),Scale of Pay (Rs.) 36600-3%-62000/-,Production,Not Mentioned,NaN
21584,NMDC Limited,Not Mentioned,Iron and Steel,Job Description Send me Jobs like this Emplo...,Hyderabad,Dy. General Manager (Safety) (E6),Scale of Pay (Rs.) 19000-450-24400/- (Pre-revi...,Production,Not Mentioned,NaN

In [94]:
df.loc[df['experience']=="Not Mentioned",'Min_Exp_years']=7
df['Min_Exp_years']=df['Min_Exp_years'].astype(int)

In [95]:
df['Max_Exp_years']=df['Max_Exp_years'].replace("",6)

In [96]:
df['Max_Exp_years'] = df['Max_Exp_years'].fillna(11)
df['Max_Exp_years'] = df['Max_Exp_years'].astype(int)

In [97]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 21317 entries, 0 to 21999
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   company              21317 non-null  object
 1   experience           21317 non-null  object
 2   industry             21317 non-null  object
 3   jobdescription       21317 non-null  object
 4   joblocation_address  21317 non-null  object
 5   jobtitle             21317 non-null  object
 6   payrate              21317 non-null  object
 7   skills               21317 non-null  object
 8   Min_Exp_years        21317 non-null  int32
 9   Max_Exp_years        21317 non-null  int32
dtypes: int32(2), object(8)
memory usage: 1.6+ MB

In [98]:
df.head()

,company,experience,industry,jobdescription,joblocation_address,jobtitle,payrate,skills,Min_Exp_years,Max_Exp_years
0,MM Media Pvt Ltd,0 - 1 yrs,Media / Entertainment / Internet,Job Description Send me Jobs like this Quali...,Chennai,Walkin Data Entry Operator (night Shift),"1,50,000 - 2,25,000 P.A",ITES,0,1
1,find live infotech,0 - 0 yrs,Advertising / PR / MR / Event Management,Job Description Send me Jobs like this Quali...,Chennai,Work Based Onhome Based Part Time.,"1,50,000 - 2,50,000 P.A. 20000",Marketing,0,0
2,Softtech Career Infosystem Pvt. Ltd,4 - 8 yrs,IT-Software / Software Services,Job Description Send me Jobs like this - as ...,Bengaluru,Pl/sql Developer - SQL,Not Disclosed by Recruiter,IT Software - Application Programming,4,8
3,Onboard HRServices LLP,11 - 15 yrs,Banking / Financial Services / Broking,Job Description Send me Jobs like this - Inv...,"Mumbai, Bengaluru, Kolkata, Chennai, Coimbator...",Manager/ad/partner - Indirect Tax - CA,Not Disclosed by Recruiter,Accounts,11,15
4,Spire Technologies and Solutions Pvt. Ltd.,6 - 8 yrs,IT-Software / Software Services,Job Description Send me Jobs like this Pleas...,Bengaluru,JAVA Technical Lead (6-8 yrs) -,Not Disclosed by Recruiter,IT Software - Application Programming,6,8

In [99]:
df.drop(columns=['experience','company','joblocation_address'],inplace=True,axis=1) ## as company js adds noise doesnt matter who hires

In [100]:
df['payrate'].value_counts().head(20)

payrate
Not Disclosed by Recruiter                                                  15483
Pay Band: PB4 (Rs.3740067000) with Academic Grade Pay of Rs.10,500/p.m.       121
Pay Band: PB4 (Rs.3740067000) with Academic Grade Pay of Rs.9,500/p.m.        115
Pay Band: PB3 (Rs.15600-39100) with Academic Grade Pay of Rs.8,000/p. m.       83
Best in the Industry                                                           83
2,00,000 - 4,00,000 P.A                                                        64
Pay Scale: PB-3 (Rs.I5600-39100) with AGP of Rs.8000/- p.m.                    63
3,00,000 - 8,00,000 P.A                                                        62
Best in Industry                                                               59
Best in the industry                                                           58
1,00,000 - 3,00,000 P.A                                                        57
3,00,000 - 5,00,000 P.A                                                        57
2,00,000 - 3,00,000 P.A                                                        52
1,00,000 - 2,00,000 P.A                                                        49
4,00,000 - 9,00,000 P.A                                                        46
10,00,000 - 20,00,000 P.A                                                      44
2,00,000 - 5,00,000 P.A                                                        44
1,00,000 - 4,00,000 P.A                                                        44
1,50,000 - 2,50,000 P.A                                                        41
2,00,000 - 7,00,000 P.A                                                        40
Name: count, dtype: int64

In [101]:
df.drop(columns=['payrate'],inplace=True,axis=1)

In [102]:
df.head()

,industry,jobdescription,jobtitle,skills,Min_Exp_years,Max_Exp_years
0,Media / Entertainment / Internet,Job Description Send me Jobs like this Quali...,Walkin Data Entry Operator (night Shift),ITES,0,1
1,Advertising / PR / MR / Event Management,Job Description Send me Jobs like this Quali...,Work Based Onhome Based Part Time.,Marketing,0,0
2,IT-Software / Software Services,Job Description Send me Jobs like this - as ...,Pl/sql Developer - SQL,IT Software - Application Programming,4,8
3,Banking / Financial Services / Broking,Job Description Send me Jobs like this - Inv...,Manager/ad/partner - Indirect Tax - CA,Accounts,11,15
4,IT-Software / Software Services,Job Description Send me Jobs like this Pleas...,JAVA Technical Lead (6-8 yrs) -,IT Software - Application Programming,6,8

In [103]:
df['jobdescription']

0        Job Description   Send me Jobs like this Quali...
1        Job Description   Send me Jobs like this Quali...
2        Job Description   Send me Jobs like this - as ...
3        Job Description   Send me Jobs like this - Inv...
4        Job Description   Send me Jobs like this Pleas...
                               ...
21995    Job Description   Send me Jobs like this Greet...
21996    Job Description   Send me Jobs like this Looki...
21997    Job Description   Send me Jobs like this Work ...
21998    Job Description   Send me Jobs like this We ar...
21999    Job Description   Send me Jobs like this Job d...
Name: jobdescription, Length: 21317, dtype: object

In [104]:
df['industry'].nunique()
df['industry'].value_counts().head(10)

industry
IT-Software / Software Services                  9123
BPO / Call Centre / ITES                         1225
Banking / Financial Services / Broking           1217
Education / Teaching / Training                  1213
Recruitment / Staffing                           1116
Internet / Ecommerce                              720
Pharma / Biotech / Clinical Research              505
Medical / Healthcare / Hospitals                  468
Automobile / Auto Anciliary / Auto Components     459
Construction / Engineering / Cement / Metals      438
Name: count, dtype: int64

In [105]:
df.head()

,industry,jobdescription,jobtitle,skills,Min_Exp_years,Max_Exp_years
0,Media / Entertainment / Internet,Job Description Send me Jobs like this Quali...,Walkin Data Entry Operator (night Shift),ITES,0,1
1,Advertising / PR / MR / Event Management,Job Description Send me Jobs like this Quali...,Work Based Onhome Based Part Time.,Marketing,0,0
2,IT-Software / Software Services,Job Description Send me Jobs like this - as ...,Pl/sql Developer - SQL,IT Software - Application Programming,4,8
3,Banking / Financial Services / Broking,Job Description Send me Jobs like this - Inv...,Manager/ad/partner - Indirect Tax - CA,Accounts,11,15
4,IT-Software / Software Services,Job Description Send me Jobs like this Pleas...,JAVA Technical Lead (6-8 yrs) -,IT Software - Application Programming,6,8

In [106]:
df['industry'].nunique()

63

In [107]:
df['industry'].value_counts()[:10]

industry
IT-Software / Software Services                  9123
BPO / Call Centre / ITES                         1225
Banking / Financial Services / Broking           1217
Education / Teaching / Training                  1213
Recruitment / Staffing                           1116
Internet / Ecommerce                              720
Pharma / Biotech / Clinical Research              505
Medical / Healthcare / Hospitals                  468
Automobile / Auto Anciliary / Auto Components     459
Construction / Engineering / Cement / Metals      438
Name: count, dtype: int64

In [108]:
result = df['industry'].value_counts(normalize=True)

threshold=0.02
result[threshold <= result]  ## series['condition'

industry
IT-Software / Software Services                  0.427968
BPO / Call Centre / ITES                         0.057466
Banking / Financial Services / Broking           0.057091
Education / Teaching / Training                  0.056903
Recruitment / Staffing                           0.052353
Internet / Ecommerce                             0.033776
Pharma / Biotech / Clinical Research             0.023690
Medical / Healthcare / Hospitals                 0.021954
Automobile / Auto Anciliary / Auto Components    0.021532
Construction / Engineering / Cement / Metals     0.020547
Name: proportion, dtype: float64

In [109]:
list =['IT-Software / Software Services','BPO / Call Centre / ITES','Banking / Financial Services / Broking' ,'Education / Teaching / Training','Recruitment / Staffing','Internet / Ecommerce',                   
'Pharma / Biotech / Clinical Research', 'Medical / Healthcare / Hospitals', 'Automobile / Auto Anciliary / Auto Components','Construction / Engineering / Cement / Metals']

In [110]:
df=df[df['industry'].isin(list)]

In [111]:
df['industry'].value_counts(normalize=True)

industry
IT-Software / Software Services                  0.553446
BPO / Call Centre / ITES                         0.074314
Banking / Financial Services / Broking           0.073829
Education / Teaching / Training                  0.073587
Recruitment / Staffing                           0.067702
Internet / Ecommerce                             0.043679
Pharma / Biotech / Clinical Research             0.030636
Medical / Healthcare / Hospitals                 0.028391
Automobile / Auto Anciliary / Auto Components    0.027845
Construction / Engineering / Cement / Metals     0.026571
Name: proportion, dtype: float64

In [112]:
df.head()

,industry,jobdescription,jobtitle,skills,Min_Exp_years,Max_Exp_years
2,IT-Software / Software Services,Job Description Send me Jobs like this - as ...,Pl/sql Developer - SQL,IT Software - Application Programming,4,8
3,Banking / Financial Services / Broking,Job Description Send me Jobs like this - Inv...,Manager/ad/partner - Indirect Tax - CA,Accounts,11,15
4,IT-Software / Software Services,Job Description Send me Jobs like this Pleas...,JAVA Technical Lead (6-8 yrs) -,IT Software - Application Programming,6,8
5,IT-Software / Software Services,Job Description Send me Jobs like this We ar...,WALK IN - As400 Developer - Pfsweb Global Serv...,IT Software - Application Programming,2,5
6,IT-Software / Software Services,Job Description Send me Jobs like this exper...,PHP Developer,IT Software - Application Programming,1,3

In [113]:
df['jobdescription'].iloc[1]

"Job Description \xa0 Send me Jobs like this - Involved with all stages of indirect taxation, including planning, execution and completion and will supervise and develop those with less experience. - Will be the primary on-site client contact for basic questions and information. - Advise clients on various critical issues related to all arena of Indirect taxes such as customs, excise, VAT, service tax etc. - Structured various transactions and agreements for indirect tax efficiencies - Ensure Strict Compliance of Central Excise & Service Tax Laws - Attending personal Hearings up to the level of Tribunal. - Develop Internal Systems to control day to day activities in terms of Central excise & service tax laws - Advice Company management on Central Excise & Service Tax matters to decide Company's policy in context of tax planning - Export formalities & documentation - Preparation & Realization of all types of refund claims - Liaison with Central Excise Department - Formalities related to establishment & operation of 100% EOU & STPI, SEZs. - Advising various clients on works contracts for all sectors - Tax planning and transaction structuring for turnkey projects including EPC contracts - Designing of documentation & internal procedures for day to day working under VAT regime - Assessment & Appeal proceedings - VAT Audits for almost all the States under the VAT for all sectors. - Would be arguing various cases before various quasi judicial authorities - Identifying potential new business leads & cross sell opportunities - Success in conversion of referrals - Ensure delivery of quality work and take day to day leadership of delivery team and make sure compliance of all aspects of taxation . Salary: Not Disclosed by Recruiter Industry: Banking / Financial Services / Broking Functional Area: Accounts , Finance , Tax , Company Secretary , Audit Role Category:Accounts Role:Taxation(Indirect) Manager Keyskills Service Tax Matters Central Excise Customs EOU VAT Audit Indirect Taxation Auditing STPI Export Tax Planning Excise Service Tax Sales Tax Desired Candidate Profile Requirements :- Qualified C.A. (preferably first/ second attempt)- Good technical skills- Expertise in the area of Indirect Taxes on various engagements for MNC or top Indian corporate houses- Experience handling Excise, Customs, Service Tax, Sales Tax etc.- Ability to apply expertise in a consultative role- Superior leadership ability- Superior relationship building- Presentation and public speaking- Ability to analyse and think differentlyIf interested, please call Jyoti on 7045597424. Education- UG: Any Graduate - Any Specialization PG:CA Doctorate:Doctorate Not Required Company Profile: Onboard HRServices LLP Leading Client of Onboard HRServices LLP Download PPT Photo 1 \xa0 View Contact Details"

In [114]:
df['jobdescription'].iloc[0]

'Job Description \xa0 Send me Jobs like this - as a developer in providing application design guidance and consultation, utilizing a thorough understanding of applicable technology, tools and existing designs. - Analyzes highly complex business requirements, designs and writes technical specifications to design or redesign complex computer platforms and applications. - Provides coding direction to less experienced staff or develops highly complex original code. - Acts as an expert technical resource for modeling, simulation and analysis efforts. - Verifies program logic by overseeing the preparation of test data, testing and debugging of programs. - Oversees overall systems testing and the migration of platforms and applications to production. - Develops new documentation, departmental technical procedures and user guides. - Leads projects, allocates and manages resources and manages the work of less experienced staff. - Assures quality, security and compliance requirements are met for supported area and oversees creation of or updates to and testing of the business continuation plan.: 7+ years application development and implementation experience. Additional Job Details: - Looking for PL/SQL developer, who has experience loading data using SQL loader. Salary: Not Disclosed by Recruiter Industry: IT-Software / Software Services Functional Area: IT Software - Application Programming , Maintenance Role Category:Programming & Design Role:Software Developer Keyskills SQL Loader PL SQL Development PLSQL Procedures Application Design Test Data Application Development Desired Candidate Profile \xa0 Education- UG: Any Graduate - Any Specialization PG:Any Postgraduate Doctorate:Doctorate Not Required Company Profile: Softtech Career Infosystem Pvt. Ltd Leading client of Softtech Career Infosystem Pvt. Ltd Download PPT Photo 1 \xa0 View Contact Details'

In [115]:
df['jobdescription'].iloc[2]

"Job Description \xa0 Send me Jobs like this Please share your Resume on : regina.mary@spire2grow.com 1. Strong background in Java/J2EE, Data Structures, Algorithms, Design Patterns and Web services like REST. 2. HTML Scripting: Angular JS OR JQuery OR Knockout or Node.js or Meteor JS 3. SOA based Software development background 4. Experience in writing unit test cases using JUnit, TestNG etc. 5. Knowledge on Open Source tools used in development process (like Git) 6. Experience with relational databases (MySQL is a plus). 7. Experience in webservers like Tomcat. 8. Ability to do software development following Agile methodology Salary: Not Disclosed by Recruiter Industry: IT-Software / Software Services Functional Area: IT Software - Application Programming , Maintenance Role Category:Programming & Design Role:Team Lead/Technical Lead Keyskills Javascript HTML JQuery Java Tomcat MySQL Rest JUnit Web Services GIT Desired Candidate Profile Education Qualification- BE/B.Tech or ME/M.Tech, MCA from Premier Institute.Experience - 6-8 yearsJob Location: BangaloreINterview Location :Bangalore\xa0Industry:Product BasedFunctional Area: IT Software - Application Programming, MaintenanceRole Category: Programming & DesignRole: Tech Lead***Note : Pay scale is open\xa0 Education- UG: B.Tech/B.E. - Any Specialization PG:Any Postgraduate - Any Specialization, MCA - Computers, M.Tech - Any Specialization Doctorate:Any Doctorate - Any Specialization Company Profile: Spire Technologies and Solutions Pvt. Ltd. Spire is a contextual search and intelligence company, founded in 2006. Spire is unleashing a wave of business transformation world over with its contextual technology. We are looking for intelligent, energetic and motivated professionals who could make a difference, and become part of our journey towards setting next-generation landmarks. Spire enables businesses take bigger leaps in decision making from Big Data analytics by charting the unexplored territories. Towards this, Spire's platform contributes exponentially. We build highly scalable, multi-tenant, distributed, service-oriented, cloud-hosted SaaS and PaaS products. Spire uses latest open-source technologies including those related to Big Data which are industry standard and widely adopted. At Spire, we are passionate about developing positively disruptive technologies that have proven to be transformational for business outcomes. Spire Technologies is adjudged as the best IT employer and a dream company to work by Times Ascent. Work culture The Spire team is a diverse group of sharp, highly driven, entrepreneurial professionals. We thrive on experimentation and innovation in an informal setup; and offer a non-routine environment with excellent benefits package. We are passionate about enabling operational excellence for world's biggest and best organizations. At Spire, you are in the team of game changers where you will have the opportunity to push the limits and become part of the company's success story. Career growth awaits you! Come join Spire! Download PPT Photo 1 \xa0 View Contact Details"

In [116]:
df['jobdescription'] = df['jobdescription'].str.replace(r'Company Profile:.*','')

df['jobdescription'] = df['jobdescription'].str.replace(r' Job Description   Send me Jobs like this ','')

C:\Users\burha\AppData\Local\Temp\ipykernel_20200\2423204718.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['jobdescription'] = df['jobdescription'].str.replace(r'Company Profile:.*','')
C:\Users\burha\AppData\Local\Temp\ipykernel_20200\2423204718.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['jobdescription'] = df['jobdescription'].str.replace(r' Job Description   Send me Jobs like this ','')

In [117]:
df.loc[:,'jobdescription'] = df['jobdescription'].str.replace(r'Job Description','').str.strip()

In [118]:
df.loc[:, 'jobdescription'] = df['jobdescription'].str.replace(r'Send me Jobs like this','', regex=True).str.replace('-','').str.strip()

In [119]:
df['jobdescription']

2        as a developer in providing application design...
3        Involved with all stages of indirect taxation,...
4        Please share your Resume on : regina.mary@spir...
5        We are currently hiring candidates willing to ...
6        experience/strong knowledge in PHP web applica...
                               ...
21995    Greetings from Morgan Stanley, We would like t...
21996    Looking for candidates with strong programming...
21997    Work with tech lead to architect and develop a...
21998    We are looking for a Senior UI Developers and ...
21999    Job description : Experience of 510 years with...
Name: jobdescription, Length: 16484, dtype: object

In [120]:
df.head()

,industry,jobdescription,jobtitle,skills,Min_Exp_years,Max_Exp_years
2,IT-Software / Software Services,as a developer in providing application design...,Pl/sql Developer - SQL,IT Software - Application Programming,4,8
3,Banking / Financial Services / Broking,"Involved with all stages of indirect taxation,...",Manager/ad/partner - Indirect Tax - CA,Accounts,11,15
4,IT-Software / Software Services,Please share your Resume on : regina.mary@spir...,JAVA Technical Lead (6-8 yrs) -,IT Software - Application Programming,6,8
5,IT-Software / Software Services,We are currently hiring candidates willing to ...,WALK IN - As400 Developer - Pfsweb Global Serv...,IT Software - Application Programming,2,5
6,IT-Software / Software Services,experience/strong knowledge in PHP web applica...,PHP Developer,IT Software - Application Programming,1,3

In [121]:
import re

def ultimate_clean(text):
    if not isinstance(text, str): return ""
    
    # PROTECT TECH TERMS (Prevents regex from killing symbols in C++, C#, .NET)
    text = text.replace('C++', 'CPP_TERM').replace('C#', 'CSHARP_TERM').replace('.NET', 'DOTNET_TERM')

    # REMOVE EMAILS, LINKS, AND PHONE NUMBERS
    text = re.sub(r'\S+@\S+', ' ', text)  # Emails
    text = re.sub(r'http\S+|www\S+', ' ', text)  # URLs
    text = re.sub(r'\d{10,}', ' ', text)  # Phone numbers (10+ digits)

    # 3. REMOVE NAUKRI-SPECIFIC NOISE (Boilerplate phrases)
    noise_patterns = [
        r'Job Description', r'Send me Jobs like this', r'Not Disclosed by Recruiter',
        r'Greetings from', r'Please share your Resume on', r'Note :', r'Pay scale is open',
        r'Download', r'PPT', r'Photo', r'Desired Candidate Profile', r'Company Profile'
    ]
    for pattern in noise_patterns:
        text = re.sub(pattern, ' ', text, flags=re.IGNORECASE)

    # 4. REMOVE SPECIAL CHARS (But keep spaces so words don't merge)
    # This turns "PHP/MySQL" into "PHP MySQL"
    text = re.sub(r'[^a-zA-Z\s]', ' ', text)

    # 5. RESTORE TECH TERMS
    text = text.replace('CPP_TERM', 'C++').replace('CSHARP_TERM', 'C#').replace('DOTNET_TERM', '.NET')

    # 6. STRIP EXTRA WHITESPACE
    text = re.sub(r'\s+', ' ', text).strip()
    
    return text

#  STEPS 

# A. Apply the main cleaning function
df['cleaned_description'] = df['jobdescription'].apply(ultimate_clean)

# Remove "View Contact Details" junk and Leading numbers
# These often survive the function because they are mixed with numbers
df['cleaned_description'] = df['cleaned_description'].str.replace(r'\d+\s*view contact details.*', '', flags=re.IGNORECASE, regex=True)
df['cleaned_description'] = df['cleaned_description'].str.replace(r'^\d+[\.\s]*', '', regex=True)

#  Remove "INR" and Salary blocks
df['cleaned_description'] = df['cleaned_description'].str.replace(r'INR\s*[\d,]*\s*[\d,]*\s*P\.A', '', flags=re.IGNORECASE, regex=True)

print("Cleaning Finished. Sample of Row 0:")
print(df['cleaned_description'].iloc[0][:500])

C:\Users\burha\AppData\Local\Temp\ipykernel_20200\3566132677.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['cleaned_description'] = df['jobdescription'].apply(ultimate_clean)
C:\Users\burha\AppData\Local\Temp\ipykernel_20200\3566132677.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['cleaned_description'] = df['cleaned_description'].str.replace(r'\d+\s*view contact details.*', '', flags=re.IGNORECASE, regex=True)
C:\Users\burha\AppData\Local\Temp\ipykernel_20200\3566132677.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['cleaned_description'] = df['cleaned_description'].str.replace(r'^\d+[\.\s]*', '', regex=True)

Cleaning Finished. Sample of Row 0:
as a developer in providing application design guidance and consultation utilizing a thorough understanding of applicable technology tools and existing designs Analyzes highly complex business requirements designs and writes technical specifications to design or redesign complex computer platforms and applications Provides coding direction to less experienced staff or develops highly complex original code Acts as an expert technical resource for modeling simulation and analysis efforts Verifies

C:\Users\burha\AppData\Local\Temp\ipykernel_20200\3566132677.py:46: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['cleaned_description'] = df['cleaned_description'].str.replace(r'INR\s*[\d,]*\s*[\d,]*\s*P\.A', '', flags=re.IGNORECASE, regex=True)

In [122]:
df['cleaned_description'][6]  # randomly selected js to check

'experience strong knowledge in PHP web application development Develop and maintain new features on Web Application development LAMP stack Handson experience in PHP Perl Python MySQL JQuery Ajax is must Strong in OOPS and must have worked in Salary INR P A Industry ITSoftware Software Services Functional Area IT Software Application Programming Maintenance Role Category Programming Design Role Software Developer Keyskills LAMP PHP MySQL JQuery Ajax Python OOPS Web Application Development Perl Web Technologies Web Services struts asp net xml soap webservices shampoo Working experience in any of the APIs like Facebook Twitter or Google would be added advantage Create highly efficient and dynamic PHP code Familiar with JavaScript frameworks like Angular React Ember and or Backbone Troubleshoot test and mainta Kinesis Management Consultant Pvt Ltd Large It Company Design develop maintain and optimize secure and scalable web applications in all phases of the development life cycle Analyze requirements and develop application designs View Contact Details'

In [123]:
df= df.rename(columns={'cleaned_description':'job_description'})

In [124]:
df.head()

,industry,jobdescription,jobtitle,skills,Min_Exp_years,Max_Exp_years,job_description
2,IT-Software / Software Services,as a developer in providing application design...,Pl/sql Developer - SQL,IT Software - Application Programming,4,8,as a developer in providing application design...
3,Banking / Financial Services / Broking,"Involved with all stages of indirect taxation,...",Manager/ad/partner - Indirect Tax - CA,Accounts,11,15,Involved with all stages of indirect taxation ...
4,IT-Software / Software Services,Please share your Resume on : regina.mary@spir...,JAVA Technical Lead (6-8 yrs) -,IT Software - Application Programming,6,8,Strong background in Java J EE Data Structures...
5,IT-Software / Software Services,We are currently hiring candidates willing to ...,WALK IN - As400 Developer - Pfsweb Global Serv...,IT Software - Application Programming,2,5,We are currently hiring candidates willing to ...
6,IT-Software / Software Services,experience/strong knowledge in PHP web applica...,PHP Developer,IT Software - Application Programming,1,3,experience strong knowledge in PHP web applica...

In [125]:
df['skills']

2        IT Software - Application Programming
3                                     Accounts
4        IT Software - Application Programming
5        IT Software - Application Programming
6        IT Software - Application Programming
                         ...
21995               IT Software - QA & Testing
21996    IT Software - Application Programming
21997    IT Software - Application Programming
21998    IT Software - Application Programming
21999         IT Software - System Programming
Name: skills, Length: 16484, dtype: object

In [126]:
def clean_skills_category(text):
    if not isinstance(text, str): return "general"
    # 1. Remove "IT Software - " prefix (it's redundant in 80% of rows)
    text = text.replace('IT Software - ', '')
    # 2. Replace special chars with spaces
    text = re.sub(r'[^a-zA-Z\s]', ' ', text)
    # 3. Clean whitespace
    return re.sub(r'\s+', ' ', text).strip().lower()

df['skills_cleaned'] = df['skills'].apply(clean_skills_category)

In [127]:
df.head()

,industry,jobdescription,jobtitle,skills,Min_Exp_years,Max_Exp_years,job_description,skills_cleaned
2,IT-Software / Software Services,as a developer in providing application design...,Pl/sql Developer - SQL,IT Software - Application Programming,4,8,as a developer in providing application design...,application programming
3,Banking / Financial Services / Broking,"Involved with all stages of indirect taxation,...",Manager/ad/partner - Indirect Tax - CA,Accounts,11,15,Involved with all stages of indirect taxation ...,accounts
4,IT-Software / Software Services,Please share your Resume on : regina.mary@spir...,JAVA Technical Lead (6-8 yrs) -,IT Software - Application Programming,6,8,Strong background in Java J EE Data Structures...,application programming
5,IT-Software / Software Services,We are currently hiring candidates willing to ...,WALK IN - As400 Developer - Pfsweb Global Serv...,IT Software - Application Programming,2,5,We are currently hiring candidates willing to ...,application programming
6,IT-Software / Software Services,experience/strong knowledge in PHP web applica...,PHP Developer,IT Software - Application Programming,1,3,experience strong knowledge in PHP web applica...,application programming

In [128]:
df['skills'].unique()

array(['IT Software - Application Programming', 'Accounts', 'ITES',
       'IT Software - Other', 'Executive Assistant',
       'IT Software - Mobile', 'Financial Services', 'Sales',
       'IT Software - QA & Testing', 'HR', 'Supply Chain',
       'IT Software - Network Administration', 'IT Software - DBA',
       'Strategy', 'Design', 'IT Software - Mainframe',
       'IT Software - Middleware', 'Marketing', 'Teaching', 'Medical',
       'IT Software - System Programming',
       'IT Software - Client/Server Programming', 'Journalism',
       'IT Software - eCommerce', 'Legal', 'Hotels',
       'IT Software - Embedded', 'IT Software - ERP', 'Site Engineering',
       'Engineering Design', 'IT Hardware',
       'Analytics & Business Intelligence', 'Production',
       'IT Software - Telecom Software', 'Architecture', 'TV',
       'Top Management', 'IT Software - Systems', 'Export',
       'Defence Forces', 'Fashion Designing', 'Travel', 'Packaging'],
      dtype=object)

In [129]:
df['skills_cleaned'].unique()

array(['application programming', 'accounts', 'ites', 'other',
       'executive assistant', 'mobile', 'financial services', 'sales',
       'qa testing', 'hr', 'supply chain', 'network administration',
       'dba', 'strategy', 'design', 'mainframe', 'middleware',
       'marketing', 'teaching', 'medical', 'system programming',
       'client server programming', 'journalism', 'ecommerce', 'legal',
       'hotels', 'embedded', 'erp', 'site engineering',
       'engineering design', 'it hardware',
       'analytics business intelligence', 'production',
       'telecom software', 'architecture', 'tv', 'top management',
       'systems', 'export', 'defence forces', 'fashion designing',
       'travel', 'packaging'], dtype=object)

In [130]:
df.drop('skills',inplace=True,axis=1)

In [131]:
df=df.rename(columns={'skills_cleaned':'skills'})

In [132]:
df

,industry,jobdescription,jobtitle,Min_Exp_years,Max_Exp_years,job_description,skills
2,IT-Software / Software Services,as a developer in providing application design...,Pl/sql Developer - SQL,4,8,as a developer in providing application design...,application programming
3,Banking / Financial Services / Broking,"Involved with all stages of indirect taxation,...",Manager/ad/partner - Indirect Tax - CA,11,15,Involved with all stages of indirect taxation ...,accounts
4,IT-Software / Software Services,Please share your Resume on : regina.mary@spir...,JAVA Technical Lead (6-8 yrs) -,6,8,Strong background in Java J EE Data Structures...,application programming
5,IT-Software / Software Services,We are currently hiring candidates willing to ...,WALK IN - As400 Developer - Pfsweb Global Serv...,2,5,We are currently hiring candidates willing to ...,application programming
6,IT-Software / Software Services,experience/strong knowledge in PHP web applica...,PHP Developer,1,3,experience strong knowledge in PHP web applica...,application programming
...,...,...,...,...,...,...,...
21995,Banking / Financial Services / Broking,"Greetings from Morgan Stanley, We would like t...",Quality Assurance - VP with Morgan Stanley Ban...,9,13,Morgan Stanley We would like to consider you f...,qa testing
21996,IT-Software / Software Services,Looking for candidates with strong programming...,Java Backend Developers for a Product Company,3,5,Looking for candidates with strong programming...,application programming
21997,Internet / Ecommerce,Work with tech lead to architect and develop a...,Full Stack Development Engineer,2,4,Work with tech lead to architect and develop a...,application programming
21998,IT-Software / Software Services,We are looking for a Senior UI Developers and ...,Sr UI Developer/ Technical Lead - Html/ CSS/ J...,7,12,We are looking for a Senior UI Developers and ...,application programming
21999,IT-Software / Software Services,Job description : Experience of 510 years with...,RF Firmware Engineers,5,10,Experience of years with most of this experien...,system programming